CREATE TABLE IF NOT EXISTS "list" (
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"torrent_id" VARCHAR(20) NOT NULL UNIQUE,
	"type" VARCHAR(20) NOT NULL,
	"tmdb_id" BIGINT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "torrents" (
	"id" VARCHAR(20) NOT NULL PRIMARY KEY,
	"folder" VARCHAR(1024) NOT NULL,
	"dest_folder" VARCHAR(1024) NULL
);